#######################################################################################
# Book settings
title: '' 
author: Xiaogang HE
email: 'hexg@nus.edu.sg'
logo                        : "favicon.png"  # A path to the book logo
exclude_patterns            : ["README.md", Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 600    # The maximum time (in seconds) each notebook cell is allowed to run.

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - html_image

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "favicon.png"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  google_analytics_id       : "UA-xxx"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://xiaoganghe.github.io/python-climate-visuals/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_repository_button     : true
  use_edit_page_button      : false
  use_issues_button         : false
  use_multitoc_numbering    : false

#######################################################################################
# Launch button settings
launch_buttons:
  binderhub_url             : "https://mybinder.org" # The URL of the BinderHub (e.g., https://mybinder.org)
  colab_url                 : https://colab.research.google.com

repository:
  url                       : https://github.com/XiaogangHe/python-climate-visuals  # The URL to your book's repository
  branch                    : master  # Which branch of the repository should be used when creating links

sphinx:
  config:
    html_extra_path: ['assets']
