name: pyCIVIL Book

channels:
  - conda-forge

dependencies:
  - scikit-learn >= 0.24
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - jupyterlab
  - notebook
  - jupytext
  - plotly
  - cartopy
  - xarray
  - netcdf4
